package com.exception;


//             ========= Program Terminated Normaly==============
public class SimpleTryCatch {
public static void main(String[] args) {

//	System.out.println("this is my first try catch blok program....");
//		int a=12;
//		int b=0;
//		try{
//		int c=a/b;
//		System.out.println(c);
//		}
//		catch(ArithmeticException e)
//		{
//			System.out.println("this is catch block exception." + e);
//		}
//		System.out.println("here ended the main method..");
//	}
//
//}




//            ========= Program Terminated Abormaly==============
            		
            		
    		try {
    		System.out.println(10/0);
    		                     //java.lang.ArithmeticException
    		}
    		catch(NullPointerException e)
    		{
    			System.out.println("this is catch block exception.");
    		}
    	}

    }
    		
            		
            		
            		
            		
            		
            		
            		
            		
            		
            		
            		
            		